#!/data/data/com.termux/files/glibc/bin/bash
clear
unset LD_PRELOAD
# Function to adjust text size based on screen width
adjust_text_size() {
    if command -v stty &> /dev/null; then
        screen_width=$(stty size | awk '{print $2}')
    else
        echo "Error: stty command not found. Unable to get screen width."
        return
    fi

    if [ -n "$screen_width" ] && [ "$screen_width" -lt 40 ]; then
        text_size="Small"
    elif [ -n "$screen_width" ] && [ "$screen_width" -lt 80 ]; then
        text_size="Medium"
    else
        text_size="Large"
    fi

    echo "Detected screen width: $screen_width"
    echo "Adjusted text size: $text_size"
}

# Function to display menu options with adjusted text size
display_menu_options() {
    adjust_text_size
    echo -e "\033[0;32m═══════════════════════════════════════"
    echo -e "             \033[0;33mMain Menu\033[0;32m"
    sleep 0.02
    echo -e "═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m1)\033[0;32m Desktop Mode taskset Auto Control   ➤"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m2)\033[0;32m Install Wine   ➤"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m3)\033[0;32m Change language   ➤"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m4)\033[0;32m Change gpu   ➤"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m5)\033[0;32m Wineesync Settings   ➤"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m6)\033[0;32m Cpu Control Settings   ➤"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m7)\033[0;32m Update Box64   ➤"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m8)\033[0;32m Update mefartbox   ➤"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
    sleep 0.02
    echo -e "\033[0;32m \033[0;36m9)\033[0;32m Exit"
    sleep 0.02
    echo -e "\033[0;32m═══════════════════════════════════════"
}

# Function to apply proot command
apply_proot_with_limit() {
    export WINEESYNC=1
    proot --bind=$PREFIX/glibc/var/run/shm:/dev/shm --bind=$PREFIX/tmp:/tmp "$@"
}

# Function to apply proot command
apply_proot() {
    export WINEESYNC=1
#    proot --bind=$PREFIX/glibc/var/run/shm:/dev/shm --bind=$PREFIX/tmp:/tmp \
        python3 $FILES/opt/Scripts/proxy.py
}

# Example usage
display_menu_options
read -p "Enter your choice: " choice

case $choice in
    1) . $FILES/opt/Scripts/language; . $FILES/opt/Scripts/gpu; . $FILES/opt/Scripts/wineesync; python3 $FILES/opt/Scripts/start-box64.py ;;
    2) bash $FILES/opt/Scripts/changewinever.sh ;;
    3) . $FILES/opt/Scripts/language01 ;;
    4) . $FILES/opt/Scripts/gpu01 ;;
    5) . $FILES/opt/Scripts/wineesync01 ;;
    6) . $FILES/opt/Scripts/cpu01 ;;
    7) pkg install -y git; unset LD_PRELOAD; export GLIBC_PREFIX=/data/data/com.termux/files/usr/glibc; export PATH=$GLIBC_PREFIX/bin:$PATH; cd ~/; git clone https://github.com/ptitSeb/box64; cd ~/box64; sed -i 's/\/usr/\/data\/data\/com.termux\/files\/usr\/glibc/g' CMakeLists.txt; sed -i 's/\/etc/\/data\/data\/com.termux\/files\/usr\/glibc\/etc/g' CMakeLists.txt; mkdir build; cd build; cmake --install-prefix $PREFIX/glibc .. -DARM_DYNAREC=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBAD_SIGNAL=ON -DSD845=ON; make -j8; make install; rm -rf ~/box64; cd ~/ ;;
    8) curl -o update https://raw.githubusercontent.com/Dark-Shiroe/mefartbox/main/update && chmod +x update && ./update ;;
    9) exit ;;
    *) echo "Incorrect option" && . $FILES/opt/Scripts/start ;;
esac
