#!/bin/bash

termux-setup-storage & sleep 4 &>/dev/null

while true; do
    if [ -d ~/storage/shared ]; then
        break
    else
        echo "Storage permission denied"
    fi
    sleep 3
done

echo "Installing termux packages"
apt-get clean
apt-get update >/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1
pkg install x11-repo -y &>/dev/null
pkg install termux-am -y &>/dev/null
pkg install xorg-xrandr -y &>/dev/null
pkg install termux-x11-nightly -y &>/dev/null
pkg install nano pulseaudio -y &>/dev/null
pkg install patchelf -y &>/dev/null
pkg install p7zip -y &>/dev/null
pkg install wget -y &>/dev/null

echo "Downloading MeFartBox"
wget -q --show-progress https://github.com/mebabo1/menano/releases/download/Box/bin.tar.gz
tar xf bin.tar.gz
x33
rm -rf bin.tar.gz
cd /sdcard/
wget -q --show-progress https://github.com/mebabo1/menano/releases/download/Box/Box64Droid01.tar.gz
tar xf Box64Droid01.tar.gz
rm -rf Box64Droid01.tar.gz
cd /data/data/com.termux/files
rm -rf opt
wget -q --show-progress https://github.com/mebabo1/menano/releases/download/Box/box64.tar.xz
tar xf box64.tar.xz
rm -rf box64.tar.xz
rm -rf usr/glibc
wget -q --show-progress https://github.com/mebabo1/menano/releases/download/Box/glibc.tar.xz
tar xf glibc.tar.xz
rm -rf glibc.tar.xz
rm -rf usr/glibc/etc/fonts
wget -q --show-progress https://github.com/mebabo1/menano/releases/download/Box/etcfonts.tar.gz
tar xf etcfonts.tar.gz
rm -rf etcfonts.tar.gz
wget -q --show-progress https://github.com/mebabo1/menano/releases/download/Box/gen.tar.gz
tar xf gen.tar.gz
rm -rf gen.tar.gz
wget -q --show-progress https://github.com/mebabo1/menano/releases/download/Box/alsa.tar
tar xf alsa.tar
rm -rf alsa.tar
cd
rm -rf test

echo "Done"
echo "To start MeFartBox run 'x11'"
