#!/bin/bash
## This page for example updating file command

cd /data/data/com.termux/files
echo "Downloading update file"

wget -q --show-progress https://raw.githubusercontent.com/Dark-Shiroe/mefartbox/main/start
mv start opt/Scripts
rm -rf $HOME/update
echo "Done"
echo "Go Fap again with x11"
